### ISSUE TITLE
Session wordlist support

### ISSUE THREAD

**Issue by rrthomas** [nuspell/nuspell#130] opened 2023-05-22 21:37 UTC
- Others, questions

# Other issues

Does nuspell support session wordlists? Note, this is not (necessarily) the same as personal wordlists, as they exist only during a given spelling session and are not loaded or saved. I can't find anything in the API, but I could be missing it…

**Comment by PanderMusubi** [comment] 2023-05-23 11:15
No, we leave this to the application calling the API. I do have an implementation for it somewhere if you want to use that in Enchant. Contact me personally, I think you have my email address.

**Comment by dimztimz** [comment] 2023-05-23 18:12
Duplicate of #129. 

Well this is the only portable way of implementing personal dictionaries. I don't see a difference with the existing issue. If you were thinking about saving and loading and managing the personal wordlist, I never intended do to that, at least not as part of the library.

**Closed as not planned by dimztimz** 2023-05-23 18:12 UTC
Labels: duplicate, enhancement

**Comment by rrthomas** [comment] 2023-05-23 18:31
@dimztimz Apologies, I opened this issue because I often find maintainers have the opposite desire, to keep separate things separate! And in this issue I was not asking for a feature to be developed, I was asking what functionality currently exists in nuspell.

From what @PanderMusubi says, it's possible to implement session support outside nuspell; I just don't understand how that's possible while retaining the ability to have user dictionary words appear in suggestions.
