### ISSUE TITLE
Nuspell hangup

### ISSUE THREAD

**Issue by baarsrj** [nuspell/nuspell#85] opened 2020-09-25 06:43 UTC
Occasionally, started from the command line to check a file, Nuspell hangs on certain lines. 
At first I assumed it was only with Dutch, but now it hangs on Danish as well.

After doing some testing, this line seemed to be the cause of the hang:

     78 af oplaget/prøver. ------------------------------------------------

After removing all lines with -- (grep -av "\-\-" ) from the input file, there was no hang any longer.
Okay, it is special. But it should not cause a hang/very long wait.

**Comment by PanderMusubi** [comment] 2020-09-25 09:48
Will look into this in October.

**Comment by dimztimz** [comment] 2020-09-26 15:01
I can confirm the issue. It is highly likely a special case of #45. In debug build it takes ~30 seconds to get a result, but in Release mode it is much faster, only few seconds.

I'd like to note that with a recent change d612c36615f36ab74b12fdfd1737f146b6ddaec9 this issue is mitigated because with the Unicode text segmentation we ignore all punctuation. To reproduce with the latest master one has to run nuspell CLI with `-s` option.

**Comment by dimztimz** [comment] 2020-09-26 15:13
Ok, I tested again, once with Dutch and again with Danish dictionary. Both cases need more analyzing.

OS: Ubuntu 20.04
Nuspell version: master, https://github.com/nuspell/nuspell/commit/d612c36615f36ab74b12fdfd1737f146b6ddaec9

Steps to reproduce in shell:

```bash
sudo apt install hunspell-nl hunspell-da
# build nuspell and from the build dir
echo "78 af oplaget/prøver. ------------------------------------------------" | ./src/nuspell/nuspell -d da_DK -s    # tests with Danish
echo "78 af oplaget/prøver. ------------------------------------------------" | ./src/nuspell/nuspell -d nl -s    # tests with Dutch

```

**Comment by PanderMusubi** [comment] 2020-09-29 11:31
Analysis is in https://github.com/nuspell/nuspell.suggestions, specifically see current situation https://github.com/nuspell/nuspell.suggestions/blob/master/measurements-unoptimized/report.md where Dutch indeed can stall suggestion generation or need very long, e.g. 45 minutes in one case. This also happens for French but nor for German or English.

A fix for 1. and 3. as described in https://github.com/nuspell/nuspell/issues/45 has been developed and leads to very good times for suggestions Dutch and other languages, see timings in https://github.com/nuspell/nuspell.suggestions/blob/master/measurements-optimized-nolog/report.md

**Comment by dimztimz** [comment] 2020-09-29 11:44
The case with Danish is NOT related to suggestions, thus I confirm that this is a different bug than #45.

```
echo "78 af oplaget/prøver. ------------------------------------------------" | \
     ./src/nuspell/nuspell -d da_DK -s -l    # tests with Danish, -l switch, hangs
echo "78 af oplaget/prøver. ------------------------------------------------" | \
     ./src/nuspell/nuspell -d nl -s -l    # tests with Dutch, -l switch, ok, fast
```

**Comment by baarsrj** [comment] 2020-10-07 11:18
Just -- is enough to make it stall.

**Comment by dimztimz** [comment] 2020-10-16 12:44
The bug lies in the two lines bellow.

https://github.com/nuspell/nuspell/blob/4e2e9a5867a9f99d1cd8b4e17719c9c3998d4aa4/src/nuspell/dictionary.cxx#L112

https://github.com/nuspell/nuspell/blob/4e2e9a5867a9f99d1cd8b4e17719c9c3998d4aa4/src/nuspell/dictionary.cxx#L122

The recusion depth is not increased on the recusive call. The quick fix should be like this line:

https://github.com/nuspell/nuspell/blob/4e2e9a5867a9f99d1cd8b4e17719c9c3998d4aa4/src/nuspell/dictionary.cxx#L134

Now, thinking about this there is a better fix and that is that break patters at the beginning and the end of the word shouldn't be considered in the recursive calls. IMO, they should work on the whole word and not on part of it. For example, given the following break patterns

```
BREAK 2
BREAK ^+
BREAK -
```
and the word `abc-+xyz`, the algorithm will first check the whole word, then it will split it to `abc` and `+xyz`, and then `+xyz` will be trimmed to `xyz` because of the break pattern `BREAK ^+`. This is considered a break pattern only for the beginning of the word, and should remain as such. This behavior also exists in Hunspell, and I think this is by accident and it should be fixed.

**Closed** 2020-10-16 13:02 UTC
Labels: bug
