### ISSUE TITLE
Personal wordlist support

### ISSUE THREAD

**Issue by rrthomas** [nuspell/nuspell#129] opened 2023-04-14 10:57 UTC
I see that there used to be personal wordlist support, but it was removed in version 4. Is there any prospect for reintroducing it?

I write in my capacity as Enchant maintainer. I would like to simplify personal wordlist support in Enchant to be like session wordlist support, namely simply a list of words that are considered correct, and remove the personal wordlist suggestion code that is complex and does not work well for all languages (not to mention, it works differently from each back-end, so could confuse users by suggesting words in a different way).

Hunspell and Aspell, the two most popular spelling libraries used by Enchant, offer personal wordlist support, so for them it would be better to use their "native" personal wordlists. Looking to the future, it would be great if Nuspell offered similar facilities, based on its superior language support. Is there any chance of that happening?

**Comment by dimztimz** [comment] 2023-04-14 17:28
Thank you for your interest. This is duplicate of #95.

**Closed** 2023-04-14 18:07 UTC
